// <auto-generated />
using System;
using IKeep.Lib.DA.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IKeep.Web.Migrations
{
    [DbContext(typeof(IKeepContext))]
    [Migration("20191001083258_AddEntityStatus")]
    partial class AddEntityStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IKeep.Lib.Models.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("FloorId");

                    b.Property<Guid?>("MapId");

                    b.Property<string>("Name");

                    b.Property<string>("Ref");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("MapId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("InstallationId");

                    b.Property<string>("Name");

                    b.Property<string>("Ref");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Corrective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClosedBy");

                    b.Property<DateTime>("ClosingDate");

                    b.Property<string>("ClosingDescription");

                    b.Property<TimeSpan>("Duration");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("GenericElementId");

                    b.Property<string>("OpenedBy");

                    b.Property<DateTime>("OpeningDate");

                    b.Property<string>("OpeningDescription");

                    b.Property<int>("Status");

                    b.Property<string>("SupplierName");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("GenericElementId");

                    b.HasIndex("UserId");

                    b.ToTable("Correctives");
                });

            modelBuilder.Entity("IKeep.Lib.Models.ElementObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("GenericElementId");

                    b.Property<Guid>("ObservationId");

                    b.HasKey("Id");

                    b.HasIndex("GenericElementId");

                    b.HasIndex("ObservationId");

                    b.ToTable("ElementObservations");
                });

            modelBuilder.Entity("IKeep.Lib.Models.ElementType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<string>("Ref");

                    b.HasKey("Id");

                    b.ToTable("ElementTypes");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Floor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BuildingId");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<string>("Ref");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Format", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Formats");
                });

            modelBuilder.Entity("IKeep.Lib.Models.GenericElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AreaId");

                    b.Property<Guid>("ElementTypeId");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<string>("Ref");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("GemericElements");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("InstallationId");

                    b.Property<string>("Result");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addres");

                    b.Property<string>("CIF");

                    b.Property<int>("CP");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<int>("EntityStatus");

                    b.Property<int>("Fax");

                    b.Property<string>("Name");

                    b.Property<int>("Phone");

                    b.Property<int>("Phone2");

                    b.Property<string>("Ref");

                    b.HasKey("Id");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("IKeep.Lib.Models.InstallationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("InstallationId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.HasIndex("UserId");

                    b.ToTable("InstallationUsers");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Map", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AreaRef");

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("FloorId");

                    b.Property<string>("ImageId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid?>("GenericElementId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("GenericElementId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Priority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Priorities");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("InstallationId");

                    b.Property<string>("PDF");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<int>("EntityStatus");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<TimeSpan>("Duration");

                    b.Property<DateTime>("EndDate");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("FormatId");

                    b.Property<Guid>("GenericElementId");

                    b.Property<int>("Period");

                    b.Property<Guid>("PriorityId");

                    b.Property<string>("Ref");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Status");

                    b.Property<string>("SupplierName");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("GenericElementId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("IKeep.Lib.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Birthplace");

                    b.Property<string>("City");

                    b.Property<string>("DNI");

                    b.Property<string>("Email");

                    b.Property<int>("EntityStatus");

                    b.Property<DateTime>("EntryTime");

                    b.Property<DateTime>("ExitTime");

                    b.Property<string>("FirstSurname");

                    b.Property<string>("ImageId");

                    b.Property<string>("LoginName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("Phone");

                    b.Property<int>("Phone2");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("SecondSurname");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IKeep.Lib.Models.UserCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CategoryId");

                    b.Property<int>("EntityStatus");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCategories");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Area", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Floor")
                        .WithMany("Areas")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IKeep.Lib.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Building", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Installation")
                        .WithMany("Buildings")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.Category", b =>
                {
                    b.HasOne("IKeep.Lib.Models.User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Corrective", b =>
                {
                    b.HasOne("IKeep.Lib.Models.GenericElement")
                        .WithMany("Correctives")
                        .HasForeignKey("GenericElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IKeep.Lib.Models.User")
                        .WithMany("Correctives")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IKeep.Lib.Models.ElementObservation", b =>
                {
                    b.HasOne("IKeep.Lib.Models.GenericElement", "GenericElement")
                        .WithMany()
                        .HasForeignKey("GenericElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IKeep.Lib.Models.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.Floor", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.GenericElement", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Area")
                        .WithMany("GenericElements")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.Inspection", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Installation")
                        .WithMany("Inspections")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.InstallationUser", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Installation", "Installation")
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IKeep.Lib.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.Map", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Floor")
                        .WithMany("Maps")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.Observation", b =>
                {
                    b.HasOne("IKeep.Lib.Models.GenericElement")
                        .WithMany("Observations")
                        .HasForeignKey("GenericElementId");
                });

            modelBuilder.Entity("IKeep.Lib.Models.Report", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Installation")
                        .WithMany("Reports")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.Task", b =>
                {
                    b.HasOne("IKeep.Lib.Models.GenericElement")
                        .WithMany("Tasks")
                        .HasForeignKey("GenericElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IKeep.Lib.Models.User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IKeep.Lib.Models.User", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IKeep.Lib.Models.UserCategory", b =>
                {
                    b.HasOne("IKeep.Lib.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IKeep.Lib.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
